config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"
  get 'home', to: 'pages#home'
  get 'dashboard', to: "pages#dashboard"
  get 'myevents', to: "events#myevents"
  get "hikes", to: "hikes#index"

  resources :events, only: %i[index show new create edit update] do
    resources :bookings, only: %i[create]
    resources :chatrooms, only: :show do
      resources :messages, only: %i[create show]
    end
    resources :items, only: %i[index show new create edit update destroy]
    resources :memories, only: %i[show new create edit update]
  end
  patch 'create_brings', to: "item_brings#create_brings", as: :update_items
  resources :bookings, only: %i[destroy]
end

app/views/shared/_card.html.erb
<% booked = !(item.bookings & Booking.where(user: current_user)).empty? %>
<li class="card_openair <%= 'booking_event' if booked %><%= 'owner_event' if item.user == current_user %>" <% if(item.class == Event.new.class ) %>data-card-events-target="card" <% elsif(item.class == Booking.new.class) %>data-card-bookings-target="card"<% end %>>
<%= link_to (event_path(item)), class: 'row anchor_card' do %>
<% if booked %>
<i class="fa-solid fa-bookmark fa-2xl bookmark_event"></i>
<h4 class="bookmark_event_text">réservé</h4>
<% end %>
<% if item.user == current_user %>
<h4 class="orga_event_text">organisateur</h4>
<% end %>
  <div class="images position-relative" style="background-image: url('<%= item.hike.image_url %>')" class="col-xs-12 col-md-4">
    <div class="group_size"><i class="fa-solid fa-users fa-xs" style="color: #ffffff;"></i><span><%= item.bookings.count + 1 %> / <%= item.group_size %></span></div>
    <div class="event_hour"><span><%= item.meeting_time.hour %>h </span> <i class="fa-solid fa-clock fa-xs" style="color: #ffffff;"></i></div>
  </div>
  <div class="card-event-stats col-12">
    <div class="d-flex justify-content-between">
      <span><strong><%= item.location %></strong></span>
      <span class="difficult <%= difficult(item)%>"><%= item.difficulty %></span>
    </div>
    <div class="d-flex justify-content-between">
    <span class="event_time"><%= item.meeting_date.strftime('%d/%m/%Y') %></span>
      <span><%= item.user.first_name %>.<%= item.user.last_name.first %> <% if item.user == current_user %><strong class="owner">(Vous)</strong> <% end %> <i class="fa-regular fa-user"></i></span>
    </div>
  </div>
<% end %>
</li>

app/views/shared/_flashes.html.erb
<% if notice %>
<div data-controller="flashes">
  <div class="alert alert-dismissible fade show m-1" role="alert" data-flashes-target="alert">
    <%= notice %>
  </div>
</div>
<% end %>
<% if alert %>
<div data-controller="flashes">
  <div class="alert alert-dismissible fade show m-1" role="alert" data-flashes-target="alert">
    <%= alert %>
  </div>
</div>
<% end %>

app/views/shared/_navbar.html.erb
<footer class="navbar-lewagon d-flex justify-content-evenly align-items-start fixed-bottom">
<%= link_to(myevents_path, class: (current_page?(myevents_path) ? 'navbar-item active' : 'navbar-item')) do %>
    <i class="fas fa-calendar-check"></i>
    <h6>Vous</h6>
  <% end %>

  <%= link_to(events_path, class: (current_page?(events_path) ? 'navbar-item active' : 'navbar-item')) do %>
    <i class="fas fa-map-marker-alt"></i>
    <h6>Explorer</h6>
  <% end %>

  <%= link_to(root_path, class: (current_page?(root_path) ? 'navbar-item active' : 'navbar-item')) do %>
    <i class="fa-solid fa-house"></i>
    <h6>Accueil</h6>
  <% end %>

  <%= link_to(hikes_path, class: (current_page?(hikes_path) ? 'navbar-item active' : 'navbar-item')) do %>
    <i class="fas fa-route"></i>
    <h6>Parcours</h6>
  <% end %>


  <%= link_to(new_event_path, class: (current_page?(new_event_path) ? 'navbar-item active' : 'navbar-item')) do %>
    <i class="fas fa-plus-square"></i>
    <h6>Créer</h6>
  <% end %>
</footer>

app/views/shared/_top_navbar.html.erb
<nav class="navbar_openair navbar navbar-expand-lg">
  <div class="container">
    <div class="navbar-title">
      <%= link_to "OpenAirConnect", root_path, class: "navbar-brand mx-auto" %>
      <%= image_tag("logo-white.png", alt: "Logo", class: "navbar-logo") %>
    </div>
    <div class="navbar-button">
      <div class="dropdown">
        <i class="fa-solid fa-user" style="color: #ffffff" id="userBtn" data-bs-toggle="dropdown" aria-expanded="false"></i>
        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="userBtn">
          <% if user_signed_in? %>
            <li>
              <%= link_to 'Se déconnecter', destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item text-danger"%>
            </li>
          <% else %>
            <li>
              <%= link_to "Se connecter", new_user_session_path, class: "dropdown-item text-success" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</nav>