config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"
  get 'home', to: 'pages#home'
  get 'dashboard', to: "pages#dashboard"
  get 'myevents', to: "events#myevents"
  get "hikes", to: "hikes#index"

  resources :events, only: %i[index show new create edit update] do
    resources :bookings, only: %i[create]
    resources :chatrooms, only: :show do
      resources :messages, only: %i[create show]
    end
    resources :items, only: %i[index show new create edit update destroy]
    resources :memories, only: %i[show new create edit update]
  end
  patch 'create_brings', to: "item_brings#create_brings", as: :update_items
  resources :bookings, only: %i[destroy]
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :hike
  belongs_to :user
  belongs_to :memory, optional: true
  has_many :items, dependent: :destroy
  has_many :bookings
  has_many :users, through: :bookings
  has_one :chatroom, dependent: :destroy

  validates :meeting_date, :location, :meeting_time, presence: true

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]

# raise if params[:query].present? || params[:date].present?

def index
  @events = policy_scope(Event.all.order(:meeting_date))

  if params[:query].present?
    @events = @events.where('location LIKE ?', "%#{params[:query]}%")
  end

  if params[:date].present?
    date = Date.parse(params[:date])
    @events = @events.where(meeting_date: date)
  end
end

  def show
    @bookings = @event.bookings
    @booking = Booking.find_by(user: current_user, event: @event)
    @mybookings = Booking.where(user: current_user)
    authorize @event
  end

  def new
    @event = Event.new
    authorize @event
  end

  def create
    @hike = Hike.create_from_strava(params[:event][:hike_id_strava])
    @event = Event.new(event_params)
    @event.hike = @hike
    @event.user = current_user
    authorize @event
    if @event.save!
      Chatroom.create!(event: @event)
      redirect_to event_path(@event)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize @event
  end

  def update
    authorize @event
  end

  def destroy
    authorize @event
    @event.destroy
    redirect_to events_path, status: :see_other
  end

  def myevents
    @myevents = Event.where(user: current_user).order(:meeting_date)
    @mybookings = Booking.joins(:event).where(user: current_user).order(:meeting_date)
    authorize @myevents
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:meeting_date, :meeting_time, :meeting_point, :group_size, :location, :difficulty, :swim, :break, :description)
  end

  def hike_params
    params.require(:event).permit(:hike_id_strava)
  end
end

app/views/events/_form.html.erb
<%= simple_form_for @event , defaults: { input_html: { class: 'input-event' } }  do |f| %>
  <%= f.input :location, label: false, placeholder: "Lieu de l'évènement" %>
  <%= f.input :meeting_date, label: "Date", as: :date, html5: true %>
  <%= f.input :meeting_time, label: "Heure" %>
  <%= f.input :group_size , label: false, placeholder: "Taille max du groupe" %>
  <%= f.input :difficulty, label: false, placeholder: "Difficulté" %>
  <div class="container d-flex justify-content-around">
    <%= f.input :swim, label: "Baignade" %>
    <%= f.input :break, label: "Pause" %>
  </div>
  <%= f.input :description, label: false, placeholder: "Description"  %>
  <%= f.button :submit, "Suivant", class: "btn btn-warning m-2" %>
<% end %>

app/views/events/edit.html.erb
<div class="container form-event" data-controller="event-route"><h1>Editer mon évènement</h1>
<%= render "form" %>

app/views/events/index.html.erb
<% content_for :title do %>
  <%= "Evènements autour de moi - OpenAirConnect" %>
<% end %>

<main data-controller="map">
<section id="searchbar" class="container-fluid pt-2">
<%= form_with url: events_path, method: :get, html: { class: 'row', data: { refresh_list_target: 'form' } } do |f| %>
<div class="row container-fluid">
    <div class="form-group col-7">
      <%= f.text_field :query,
                        class: "form-control btn_search",
                        placeholder: 'lieu',
                        value: params[:query],
                        data: {
                          refresh_list_target: 'searchInput',
                      } %>
    </div>
    <div class="form-group col-5">
    <% if(params[:date].nil?)
        placedate = 'date'
      else
        placedate = params[:date]
      end
    %>
      <%= date_field_tag :date,
                          params[:date],
                          class: 'form-control btn_search btn_flat',
                          placeholder: placedate,
                          data: { controller: 'flatpickr' } %>
    </div>
  </div>
  <div class="form-group col-12">
    <%= button_tag 'Rechercher', class: 'openair_btn w-100', type: 'submit' %>
  </div>
<% end %>
<div data-refresh_list_target="list">
</div>
</section>

<%
def difficult(e)
  case e.difficulty
  when 'Facile'
    'facile'
  when 'Balade'
    'balade'
  when 'Intermédiaire'
    'inter'
  when 'Difficile'
    'difficile'
  when 'Sportif'
    'sportif'
  end
end
  %>

<section id="home" data-controller="card-events">

<div class="container">
      <ul class="row d-flex justify-content-evenly p-4 g-2" data-card-events-target="list_cards">
  <% @events.each do |event| %>
    <%= render 'shared/card', item: event %>
  <% end %>

  </ul>
</div>

</section>

</main>

app/views/events/myevents.html.erb
<% content_for :title do %>
  <%= "Mes évènements - OpenAirConnect" %>
<% end %>

<%

def difficult(e)
  case e.difficulty
  when 'Facile'
    'facile'
  when 'Balade'
    'balade'
  when 'Intermédiaire'
    'inter'
  when 'Difficile'
    'difficile'
  when 'Sportif'
    'sportif'
  end
end
%>

<div>
  <ul id="myTab" role="tablist">
    <li class="nav-item" role="presentation">
      <a class="openair_btn nav-link active" id="myevents-tab" data-bs-toggle="tab" href="#myevents" role="tab" aria-controls="myevents" aria-selected="true">Mes évènements</a>
    </li>
    <li class="nav-item" role="presentation">
      <a class="openair_btn nav-link" id="bookings-tab" data-bs-toggle="tab" href="#bookings" role="tab" aria-controls="bookings" aria-selected="false">Réservations</a>
    </li>
  </ul>

  <div class="tab-content" id="myTabContent">
    <div class="tab-pane fade show active" id="myevents" role="tabpanel" aria-labelledby="myevents-tab">
      <section data-controller="card-events">
        <div class="container">
            <ul class="row d-flex justify-content-evenly p-4 g-2" data-card-events-target="list_cards">
            <% @myevents.each do |event| %>
              <%= render 'shared/card', item: event %>
            <% end %>
          </ul>
        </div>
      </section>
    </div>
    <div class="tab-pane fade" id="bookings" role="tabpanel" aria-labelledby="bookings-tab">
      <section data-controller="card-bookings">
        <div class="container">
              <ul class="row d-flex justify-content-evenly p-4 g-2" data-card-bookings-target="list_cards">
            <% @mybookings.each do |booking| %>
                  <%= render 'shared/card', item: booking.event %>
            <% end %>
          </ul>
        </div>
      </section>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<% content_for :title do %>
  <%= "Créer un nouvel évènement - OpenAirConnect" %>
<% end %>
<div class="container form-event" data-controller="event-route" data-event-route-strava-api-key-value="<%=ENV['STRAVA_API_KEY'] %>"><h1 class="home-headings">Nouvel évènement</h1>

<%= simple_form_for @event , defaults: { input_html: { class: 'input-event' } }  do |f| %>

  <%= f.input :location, label: false, placeholder: "Lieu de l'évènement", :input_html => { data: { event_route_target: :location }}, class: "input-event" %>
  <%= f.input :meeting_date, as: :string, placeholder: 'Date', label: false, input_html: { data: { controller: 'flatpickr' }, class: 'btn_search bttn_flat' } %>

  <%= f.input :meeting_time, placeholder: 'heure', label: false, :minute_step => 15 %>
  <%= f.input :group_size, prompt: "Taille du groupe", collection: (2..20),label: false %>
  <%= f.input :difficulty, collection: ['Facile', 'Balade', 'Intermédiaire', 'Difficile', 'Sportif'], prompt: "Difficulté", label: false, class: "input-event"  %>
  <div class="container d-flex justify-content-around">
    <input type="checkbox" id="swim" name="swim" unchecked class="radio">
    <label for="swim">Baignade</label>
    <input type="checkbox" id="break" name="break" unchecked class="radio">
    <label for="break">Pauses</label>

  </div>
  <%= f.input :description, label: false, placeholder: "Description"  %>

  <%# BOUTON SUIVANT POUR RECHERCHER LES HIKES PAR RAPPORT AU LIEU %>
  <button data-action="click->event-route#displayRoutes" class="openair_btn">Suivant</button>

  <div class="container" data-controller="choose-hike">
  <section class="routes-results" data-event-route-target="results" id="myroutes" >


  </section>

  <section class="routes-results d-none" data-event-route-target="hidden" >
    <%= f.input :hike_id_strava,  :as => :hidden, :input_html => { value: "3109521128044970500", data: {choose_hike_target: :chosenHike} }   %>  <%# LA VALEUR EST L'ID DE LA ROUTE DE STRAVA%>

    <%= f.input :meeting_point, label: false, placeholder: "Point de rendez-vous"  %>

  <%# BOUTON POUR SOUMETTRE LE FORMULAIRE %>
  <%= f.button :submit, "Créer mon évènement", class:"openair_btn" %>
  </section>
</div>
  <% end %>

</div>

app/views/events/show.html.erb
<% content_for :title do %>
  <%= "Evènement de #{@event.user.first_name} - OpenAirConnect" %>
<% end %>

<section id="show" data-controller="weather">
  <div class="row m-0 show_hike_map position-relative">
    <%= image_tag @event.hike.image_url,  class: 'col-12 p-0' %>
    <h4 class="position-absolute text-center bottom-0 m-0" data-weather-target="location"><%= @event.location %></h4>
  </div>
  <div class="show_hike_details p-3">
    <h2 class="text-center"><%= @event.hike.title.split(':', 2)[1] %></h2>
    <div class="hike_stats d-flex justify-content-between">
    <p><i class="fa-solid fa-arrow-up-right-dots"></i> <strong> <%= @event.hike.elevation %> m</strong></p>
    <p><i class="fa-solid fa-person-hiking"></i> <strong><%= @event.hike.distance.floor(1) %> km</strong></p>
    <p><i class="fa-regular fa-clock"></i> <strong><%= (@event.hike.duration / 60 / 60) %>h<%= (@event.hike.duration / 60) % 60 %>min</strong></p>
    </div>
  </div>
  <div class="show_event_details d-flex justify-content-center align-items-center flex-column">
    <div class="show_owner_event">
      <h6>Organisateur : <%= @event.user.first_name %>. <%= @event.user.last_name.first %>  <strong><%= '( Vous )' if current_user == @event.user %></strong></h6>
    </div>
    <div class="animation text-center">
    <h6 class="users_list_head">Participants</h6>
    <div class="users_list">
      <% @bookings.each do |booking| %>
      <div class="user_booking"><%= booking.user.first_name %> <%= booking.user.last_name %></div><% if(@bookings.last != booking) %>,&nbsp; <% end %>
      <% end %>
    </div>
    </div>
      <% if !@mybookings.where(event: @event).empty? %>
      <h6 class="participate participate_event">Vous participez à cet évènement </h6>
      <%= button_to "Se désinscrire", booking_path(@booking), method: :delete, class: 'openair_btn participate_event' %>
      <% elsif current_user != @event.user %>
      <%= button_to "Rejoindre l'évènement", event_bookings_path(@event), method: :post, class: 'openair_btn participate_event' %>
      <% end %>
    <div class="details_stats col-12 container row">
      <div class="d-flex justify-content-between">
        <h6>Date de l'évènement : <span data-weather-target="date_event"><%= @event.meeting_date.strftime('%d/%m/%Y') %></span></h6>
        <h6>Horaire: <span><%= @event.meeting_time.hour   %>h<%= @event.meeting_time.min %></span></h6>
      </div>
      <div>
        <h6>Point de rendez-vous : <span><%= @event.meeting_point %></span></h6>
      </div>
    <div class="d-flex">
      <div class="bool_events">
        <div class="bool_stats text-center">
          <i class="d-flex justify-content-center align-items-center bool-true fa-solid fa-user"></i>
          <h6 class="d-flex flex-column px-3"><%= @event.bookings.count + 1 %> / <%= @event.group_size %></h6>
        </div>
          <div class="bool_stats text-center">
            <span data-weather-target="icon" class="d-flex justify-content-center align-items-center bool-true"></span>
            <h6 class="d-flex flex-column"><span>Météo</span></h6>
          </div>
        <% if @event.swim == true %>
          <div class="bool_stats text-center">
            <i class="d-flex justify-content-center align-items-center bool-true fa-solid fa-person-swimming "></i>
            <h6>Baignade</h6>
          </div>
        <% end %>
        <% if @event.break? %>
        <div class="bool_stats text-center">
          <i class="d-flex justify-content-center align-items-center bool-true fa-solid fa-cookie-bite"></i>
          <h6>Pauses</h6>
        </div>
        <% end %>
        </div>
      </div>
    <div class="event_stats container row mx-auto">
        <% if ( @event.items.count > 0 && !@mybookings.where(event: @event).empty? )|| (@event.items.count > 0 && @event.user == current_user ) %>
        <h6 class="col-12 list_items_btn btn-success"><%= link_to event_items_path(event_id: @event.id) do %><i class="fa-sharp fa-solid fa-clipboard"></i> Voir la liste <% end %></h6>
        <% elsif !@mybookings.where(event: @event).empty? || @event.user == current_user %>
        <h6 class="col-12 list_items_btn"><%= link_to new_event_item_path(event_id: @event.id) do %><i class="fa-sharp fa-solid fa-clipboard"></i> Ajouter une liste <% end %></h6>
        <% end %>
      </div> <!-- btn list -->
      <div>
        <p class="para_desc_show"><%= @event.description %></p>
      </div>
    </div>
  </div>
<% if (!@mybookings.where(event: @event).empty?) || (@event.user == current_user) %>
  <%= link_to (event_chatroom_path(@event, @event.chatroom)), class: 'btn_message' do %>
    <i class="fa-solid fa-message"></i>
  <% end %>
<% end %>
</div>
<div class="d-flex justify-content-center">
  <%= link_to "Annuler l'évènement", '#', class:'destroy_event' %>
</div>
</section>